"use client";

import { FormEvent, useState } from "react";

export function NewsletterSignup() {
  const [status, setStatus] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const email = new FormData(form).get("email"); setStatus("Submitting…"); try { const response = await fetch("/api/newsletter", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const payload = await response.json() as { error?: string; verificationUrl?: string; deliveryConfigured?: boolean }; if (!response.ok) throw new Error(payload.error || "Subscription failed."); setStatus(payload.deliveryConfigured ? "Check your inbox to verify your subscription." : `Thanks — you are on the list. Email delivery is still being set up, so the confirmation will arrive once it is live.${payload.verificationUrl ? ` (dev: ${payload.verificationUrl})` : ""}`); form.reset(); } catch (error) { setStatus(error instanceof Error ? error.message : "Subscription failed."); } }
  return <section className="home-newsletter" aria-labelledby="newsletter-title"><div className="newsletter-copy"><p className="home-kicker">Notes from the lab</p><h2 id="newsletter-title">Get the next useful release.</h2><p>Receive a short notification when Yusuf publishes an article, research note, publication, tutorial, or selected system update.</p></div><form className="newsletter-form" onSubmit={submit}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" /><button type="submit">Subscribe</button><small>Double opt-in is required. You can unsubscribe at any time.</small><p aria-live="polite">{status}</p></form></section>;
}
