import { redirect } from "next/navigation";
import { isAdminSession } from "@/admin/auth";
import { getGithubSnapshot } from "@/integrations/github";
import { getWakatimeSnapshot } from "@/integrations/wakatime";
import { getRuntimeConfig } from "@/lib/runtime-config";

export const dynamic = "force-dynamic";

export default async function AdminIntegrationsPage() { if (!(await isAdminSession())) redirect("/admin/login"); const [github, wakatime] = await Promise.all([getGithubSnapshot(), getWakatimeSnapshot()]); const runtime = getRuntimeConfig(); return <section className="admin-panel"><p className="eyebrow">Admin / Integrations</p><h1>Source synchronization</h1><p className="lede">External activity is fetched server-side, cached, labeled by state, and never treated as an authored achievement claim.</p><div className="project-grid"><article className="project-card"><p className="meta">GitHub / {github.state}</p><h2>{github.username}</h2><p>{github.publicRepos ?? "No repository count"} public repositories · {github.contributions ?? "Contribution calendar pending"} contributions.</p><p className="provenance">Refreshed {github.refreshedAt}. {github.tokenConfigured ? "Server token configured." : "Add GITHUB_TOKEN for contribution calendar data."}</p><a className="text-link" href={github.profileUrl}>Open public profile</a></article><article className="project-card"><p className="meta">WakaTime / {wakatime.state}</p><h2>{wakatime.hours === null ? "Activity pending" : `${wakatime.hours} hours`}</h2><p>Seven-day coding activity is shown only when a server-only API key is configured.</p><p className="provenance">Refreshed {wakatime.refreshedAt}. {wakatime.tokenConfigured ? "Key configured; refresh failed or returned no total." : "Add WAKATIME_API_KEY to enable synchronization."}</p></article></div><section className="detail-section"><h2>Backend readiness</h2><p><strong>Database:</strong> {runtime.database.provider} / {runtime.database.ready ? "ready" : `missing ${runtime.database.missing.join(", ")}`}</p><p><strong>AI:</strong> {runtime.ai.provider} / {runtime.ai.ready ? "ready" : `missing ${runtime.ai.missing.join(", ")}`}</p><p><strong>Newsletter:</strong> {runtime.newsletter.provider} / {runtime.newsletter.ready ? "ready" : `missing ${runtime.newsletter.missing.join(", ")}`}</p></section><section className="detail-section"><h2>Required environment values</h2><p><code>GITHUB_USERNAME</code> defaults to <code>SAHEED2010</code>. <code>GITHUB_TOKEN</code> is optional for public repository data and required for contribution calendar data. <code>WAKATIME_API_KEY</code> remains server-only.</p><p className="provenance">Admin authentication also requires <code>PORTFOLIO_ADMIN_PASSWORD_SHA256</code> and <code>PORTFOLIO_SESSION_SECRET</code>. Never commit <code>.env.local</code> or tokens.</p></section></section>; }
